### ISSUE TITLE
Some links are broken in the package website

### ISSUE THREAD

**Issue by see24** [LandSciTech/pfocal#23]
For example if I click References and the pfocal I get a 404. This is the url of the page that is not found https://landscitech.github.io/pfocal/reference/pfocal.html

**Comment by VLucet** [comment]
Hmm, yes, weird issue due to the wrong naming of the html pages because I changed some function names.

**Comment by VLucet** [comment]
Guess I just had to change the html pages name. Might have been a pkgdown bug for all i know.
