### ISSUE TITLE
Release pfocal 1.0.0

### ISSUE THREAD

**Issue by VLucet** [LandSciTech/pfocal#27]
First release:

* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `devtools::build_readme()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [ ] `rhub::check_for_cran()`
* [ ] `rhub::check(platform = 'ubuntu-rchk')`
* [ ] `rhub::check_with_sanitizers()`
* [x] Review pkgdown reference index for, e.g., missing topics
* [ ] `rhub::check_on_debian()`
* ~Draft blog post~

Submit to CRAN:
* [x] `usethis::use_version('major')`
* [x] RUN AGAIN `urlchecker::url_check()`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [ ] `usethis::use_dev_version()`
* [ ] `usethis::use_news_md()`
* [ ] Finish blog post
* [ ] Tweet
* [ ] Add link to blog post in pkgdown news menu

**Comment by see24** [comment]
Need to make the description longer 

and rcmd check has this note
```
> checking installed package size ... NOTE
    installed size is  6.7Mb
    sub-directories of 1Mb or more:
      libs   6.4Mb
```
I am getting an error when I try to run rhub::check_for_cran().
```
results <- rhub::check_for_cran(email = "sarah.endicott@ec.gc.ca")
-  Building package
Error: 
Build failed, standard output:

* checking for file 'pfocal/DESCRIPTION' ... OK
* preparing 'pfocal':
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to build vignettes
      -----------------------------------
* installing *source* package 'pfocal' ...
** using staged installation
** libs
Warning in system(cmd) : 'make' not found
ERROR: compilation failed for package 'pfocal'
* removing 'C:/Users/ENDICO~1/AppData/Local/Temp/RtmpIBwrEd/Rinst2bfc7d613e6/pfocal'
      -----------------------------------
ERROR: package installation failed

Standard error:

Warning in cleanup_pkg(pkgdir, Log) :
  unable to run 'make clean' in 'src'
```

**Comment by VLucet** [comment]
Yup the note about size is not a problem as far as i know. Unsure about the make clean issue, could be a bug on r-hub.

**Comment by see24** [comment]
@VLucet Do you think it is related to this? https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/
I am trying to figure out if I should install RTools42. Not sure if that will mess up RTools40 or if it would help at all...

**Comment by VLucet** [comment]
I dont think it is, it looks like the default on Rhub is still Rtools40, but I admit this is a little above my head. It's happened to me to have stuff pop up on Rhub and then disappear the next time I try. Did you check if the warning is repeated?

**Comment by see24** [comment]
Ya I tried it just now with a few different configurations:
`rhub::check_with_sanitizers`, `rhub::check(platform = 'windows-x86_64-devel')`, `rhub::check(platform = 'ubuntu-rchk')`, and `rhub::check_for_cran` and they all had the same error message. `devtools::check_win_devel()` was fine though. I just re-enabled the Github Actions to see if those work.

**Comment by VLucet** [comment]
Good call on the GA, lets see.

**Comment by see24** [comment]
Looks like it is probably an Rhub issue so we can go ahead.
